package ru.skpari.core.services.commission;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5-jbossorg-1
 * 2018-10-19T17:54:42.346+03:00
 * Generated source version: 3.2.5-jbossorg-1
 *
 */
@WebServiceClient(name = "SendCatsService",
                  wsdlLocation = "file:/C:/develop/wildfly14/bin/./SendCats.wsdl",
                  targetNamespace = "http://skpari.ru/core/services/commission/")
public class SendCatsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://skpari.ru/core/services/commission/", "SendCatsService");
    public final static QName SendCatsPort = new QName("http://skpari.ru/core/services/commission/", "SendCatsPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/develop/wildfly14/bin/./SendCats.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SendCatsService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/develop/wildfly14/bin/./SendCats.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SendCatsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SendCatsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendCatsService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SendCatsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SendCatsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SendCatsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SendCatsPort
     */
    @WebEndpoint(name = "SendCatsPort")
    public SendCatsPort getSendCatsPort() {
        return super.getPort(SendCatsPort, SendCatsPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendCatsPort
     */
    @WebEndpoint(name = "SendCatsPort")
    public SendCatsPort getSendCatsPort(WebServiceFeature... features) {
        return super.getPort(SendCatsPort, SendCatsPort.class, features);
    }

}
