package ru.skpari.core.services.commission;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5-jbossorg-1
 * 2018-10-19T17:54:42.330+03:00
 * Generated source version: 3.2.5-jbossorg-1
 *
 */
@WebService(targetNamespace = "http://skpari.ru/core/services/commission/", name = "SendCatsPort")
@XmlSeeAlso({ru.skpari.core.domain.commission.ObjectFactory.class, ru.skpari.core.messages.commission.ObjectFactory.class})
public interface SendCatsPort {

    @WebMethod
    @RequestWrapper(localName = "getCat", targetNamespace = "http://skpari.ru/core/messages/commission/", className = "ru.skpari.core.messages.commission.GetCat")
    @ResponseWrapper(localName = "responseCat", targetNamespace = "http://skpari.ru/core/messages/commission/", className = "ru.skpari.core.messages.commission.ResponseCat")
    @WebResult(name = "Cat", targetNamespace = "")
    public ru.skpari.core.domain.commission.CatType getCat() throws GetFaultMessage;
}
